clear
clc

global params;
params = zeros(5,1);
f = figure('Units','inches','Position',[2,2,6,6]);
paramPanel = uipanel(f,'Position',[0.05 0.05 0.9 0.2]);
figPanel = uipanel(f,'Position',[0.05,.3,.9,.65]);
figAxis = axes(figPanel);
Slider1 = uicontrol(paramPanel, 'style','slide',...
    'unit','normalized',...
    'position',[.05 .05 .4 .2],...
    'min',-5,'max',5,'val',0);
Slider2 = uicontrol(paramPanel, 'style','slide',...
    'unit','normalized',...
    'position',[.05 .3 .4 .2],...
    'min',-5,'max',5,'val',0);
Slider3 = uicontrol(paramPanel, 'style','slide',...
    'unit','normalized',...
    'position',[.05 .55 .4 .2],...
    'min',-5,'max',5,'val',0);
Slider4 = uicontrol(paramPanel, 'style','slide',...
    'unit','normalized',...
    'position',[.5 .05 .4 .2],...
    'min',-5,'max',5,'val',0);
Slider5 = uicontrol(paramPanel, 'style','slide',...
    'unit','normalized',...
    'position',[.5 .3 .4 .2],...
    'min',-5,'max',5,'val',0);

for i = 1:100
   params(1) = Slider1.Value;
   params(2) = Slider2.Value;
   params(3) = Slider3.Value;
   params(4) = Slider4.Value;
   params(5) = Slider5.Value;
   disp(params);
   pause(.05);
end






