%[y,fs]=audioread('villagerDeath.ogg');
%[y1,fs1]=audioread('villagerMumbles.ogg');


ParamMatrix = ...
   [4, -8, 4;... LOW
    4, -8, 6;...
    4, -6, 4;...
    4, -6, 6;...
    6, -8, 4;...
    6, -8, 6;...
    6, -6, 4;...
    6, -6, 6;... MID
    6, -6, 8;...
    6, -4, 6;...
    6, -4, 8;...
    8, -6, 6;...
    8, -6, 8;...
    8, -4, 6;...
    8, -4, 8];% HIGH
average = zeros(1,15);
surviving = zeros(1,15);
for i = 1:size(ParamMatrix,1)
    ParamS = 10^ParamMatrix(i,1);
    ParamC = 10^ParamMatrix(i,2);
    ParamA = 10^ParamMatrix(i,3);
    [average(i), surviving(i)] = MainScriptFunction(ParamS, ParamC, ParamA, i);
end
clf
load gong.mat;
sound(y)
hold on
legend('Average Height','Number Surviving')
yyaxis left
plot(average);
yyaxis right
plot(surviving);